config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :image, presence: true
  validates :content, presence: true,
            length: { maximum: 255 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # validates :user_image, presence: true
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  # has_many :favorite_pictures, through: :favorites, source: :picture
  mount_uploader :user_image, ImageUploader 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    elsif @picture.save
      PictureMailer.picture_mail(@picture).deliver
      redirect_to pictures_path, notice: "投稿しました！"
    else
      render :new
    end
  end

  def edit
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "ブログを削除しました"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h2>お気に入り一覧</h2>
<table>
  <tr>
    <th>投稿</th>
    <th>投稿者</th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.picture.content %></td>
    <td><%= favorite.picture.user.name%></td>
    <td><%= link_to 'お気に入りを確認する', picture_path(favorite.picture.id) %></td>
  </tr>
<% end %>
</table>

<%= link_to '投稿一覧', pictures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reminiscence</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <nav class="navigation">
        <div class="header-logo">
          <%= link_to("Reminiscence", new_session_path) %>
          <%= image_tag 'reminisence-icon.png', :size => '40x30'%>
        </div>
        <ul class="header-menus">
          <% if logged_in? %>
            <li>
            <%= link_to("Profile", user_path(current_user.id)) %>
            </li>
            <li>
            <%= link_to("Logout", session_path(current_user.id), method: :delete) %>
            </li>
          <% else %>
            <li>
            <%= link_to("Sign up", new_user_path) %>
            </li>
            <li>
            <%= link_to("Login", new_session_path) %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
    <div class="push"></div>
    <footer>
      <ul class="footer-logo" >
        <li>
          課題 写真共有アプリ
        </li>
      </ul>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="picture_image">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to '投稿一覧', pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>

  <p>文章:<%= @picture.content %></p>
  <p>画像:<%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集する</h2>
<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>投稿</th>
    <th>投稿者</th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.content %></td>
    <td><%= picture.user.name%></td>
    <td><%= link_to '詳細を確認する', picture_path(picture.id) %></td>
    <% if picture.user == current_user %>
    <td><%= link_to "投稿を編集する", edit_picture_path(picture.id) %></td>
    <td><%= link_to '投稿を削除する', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' }%></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= link_to '新しく投稿する', new_picture_path %>

app/views/pictures/new.html.erb
<h2>投稿する</h2>
<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<p>文章: <%= @picture.content %></p>
<p>画像: <%= image_tag @picture.image.url %></p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to '投稿一覧', pictures_path %>
<%= link_to 'お気に入り一覧', favorites_path %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :user_image %>
  <%= f.file_field :user_image %>
  
  <%= f.submit "edit my account" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>プロフィール画像:
<%= if @user.user_image.present?
        image_tag @user.user_image.url 
    else
        image_tag "baby-reminiscence"
    end
        %></p>

<%= link_to "プロフィールを編集する", edit_user_path(@user.id) %><br>
<%= link_to 'お気に入り一覧', favorites_path %>
<br>
<%= link_to '新しく投稿する', new_picture_path %>
<%= link_to '投稿一覧', pictures_path %>